export const bigDistrict = [
  { id: 1, value: "Hà Nội" },
  { id: 2, value: "Hồ Chí Minh" },
  { id: 3, value: "Cần Thơ" },
  { id: 4, value: "Đà Nẵng" },
  { id: 5, value: "Đồng Nai" },
  { id: 6, value: "Hải Phòng" },
  { id: 7, value: "An Giang" },
  { id: 8, value: "Bà Rịa Vũng Tàu" },
  { id: 9, value: "Bắc Giang" },
  { id: 10, value: "Bắc Kạn" },
  { id: 11, value: "Bạc Liêu" },
  { id: 12, value: "Bắc Ninh" },
  { id: 13, value: "Bến Tre" },
  { id: 14, value: "Bình Định" },
  { id: 15, value: "Bình Dương" },
  { id: 16, value: "Bình Phước" },
  { id: 17, value: "Bình Thuận" },
  { id: 18, value: "Cà Mau" },
  { id: 19, value: "Cao Bằng" },
  { id: 20, value: "Đắk Lắk" },
  { id: 21, value: "Đắk Nông" },
  { id: 22, value: "Điện Biên" },
  { id: 23, value: "Đồng Tháp" },
  { id: 24, value: "Gia Lai" },
  { id: 25, value: "Hà Giang" },
  { id: 26, value: "Hà Nam" },
  { id: 27, value: "Hà Tĩnh" },
  { id: 28, value: "Hải Dương" },
  { id: 29, value: "Hậu Giang" },
  { id: 30, value: "Hòa Bình" },
  { id: 31, value: "Hưng Yên" },
  { id: 32, value: "Khánh Hòa" },
  { id: 33, value: "Kiên Giang" },
  { id: 34, value: "Kon Tum" },
  { id: 35, value: "Lai Châu" },
  { id: 36, value: "Lâm Đồng" },
  { id: 37, value: "Lạng Sơn" },
  { id: 38, value: "Lào Cai" },
  { id: 39, value: "Long An" },
  { id: 40, value: "Nam Định" },
  { id: 41, value: "Nghệ An" },
  { id: 42, value: "Ninh Bình" },
  { id: 43, value: "Ninh Thuận" },
  { id: 44, value: "Phú Thọ" },
  { id: 45, value: "Phú Yên" },
  { id: 46, value: "Quảng Bình" },
  { id: 47, value: "Quảng Nam" },
  { id: 48, value: "Quảng Ngãi" },
  { id: 49, value: "Quảng Ninh" },
  { id: 50, value: "Quảng Trị" },
  { id: 51, value: "Sóc Trăng" },
  { id: 52, value: "Sơn La" },
  { id: 53, value: "Tây Ninh" },
  { id: 54, value: "Thái Bình" },
  { id: 55, value: "Thái Nguyên" },
  { id: 56, value: "Thanh Hóa" },
  { id: 57, value: "Thừa Thiên Huế" },
  { id: 58, value: "Tiền Giang" },
  { id: 59, value: "Trà Vinh" },
  { id: 60, value: "Tuyên Quang" },
  { id: 61, value: "Vĩnh Long" },
  { id: 62, value: "Vĩnh Phúc" },
  { id: 63, value: "Yên Bái" },
];

const vnNull = [];

const haNoi = [
  { id: 1, value: "Sơn Tây" },
  { id: 2, value: "Ba Đình" },
  { id: 3, value: "Bắc Từ Liêm" },
  { id: 4, value: "Cầu Giấy" },
  { id: 5, value: "Đống Đa" },
  { id: 6, value: "Hai Bà Trưng" },
  { id: 7, value: "Hà Đông" },
  { id: 8, value: "Hoàn Kiếm" },
  { id: 9, value: "Hoàng Mai" },
  { id: 10, value: "Long Biên" },
  { id: 11, value: "Nam Từ Liêm" },
  { id: 12, value: "Tây Hồ" },
  { id: 13, value: "Thanh Xuân" },
  { id: 14, value: "Ba Vì" },
  { id: 15, value: "Chương Mỹ" },
  { id: 16, value: "Đan Phượng" },
  { id: 17, value: "Đông Anh" },
  { id: 18, value: "Gia Lâm" },
  { id: 19, value: "Hoài Đức" },
  { id: 20, value: "Mê Linh" },
  { id: 21, value: "Mỹ Đức" },
  { id: 22, value: "Phú Xuyên" },
  { id: 23, value: "Phúc Thọ" },
  { id: 24, value: "Quốc Oai" },
  { id: 25, value: "Sóc Sơn" },
  { id: 26, value: "Thanh Trì" },
  { id: 27, value: "Thanh Oai" },
  { id: 28, value: "Thạch Thất" },
  { id: 29, value: "Thường Tín" },
  { id: 30, value: "Ứng Hòa" },
];
const hoChiMinh = [
  { id: 1, value: "Thủ Đức" },
  { id: 2, value: "Quận 1" },
  { id: 3, value: "Quận 3" },
  { id: 4, value: "Quận 4" },
  { id: 5, value: "Quận 5" },
  { id: 6, value: "Quận 6" },
  { id: 7, value: "Quận 7" },
  { id: 8, value: "Quận 8" },
  { id: 9, value: "Quận 10" },
  { id: 10, value: "Quận 11" },
  { id: 11, value: "Quận 12" },
  { id: 12, value: "Gò Vấp" },
  { id: 13, value: "Tân Bình" },
  { id: 14, value: "Tân Phú" },
  { id: 15, value: "Bình Thạnh" },
  { id: 16, value: "Phú Nhuận" },
  { id: 17, value: "Bình Tân" },
  { id: 18, value: "Củ Chi" },
  { id: 19, value: "Hóc Môn" },
  { id: 20, value: "Bình Chánh" },
  { id: 21, value: "Nhà Bè" },
  { id: 22, value: "Cần Giờ" },
];

const canTho = [
  { id: 1, value: "Bình Thủy" },
  { id: 2, value: "Cái Răng" },
  { id: 3, value: "Ninh Kiều" },
  { id: 4, value: "Ô Môn" },
  { id: 5, value: "Thốt Nốt" },
  { id: 6, value: "Cờ Đỏ" },
  { id: 7, value: "Phong Điền" },
  { id: 8, value: "Thới Lai" },
  { id: 9, value: "Vĩnh Thạnh" },
];

const daNang = [
  { id: 1, value: "Cẩm Lệ" },
  { id: 2, value: "Hải Châu" },
  { id: 3, value: "Hòa Vang" },
  { id: 4, value: "Liên Chiểu" },
  { id: 5, value: "Ngũ Hành Sơn" },
  { id: 6, value: "Sơn Trà" },
  { id: 7, value: "Thanh Khê" },
  { id: 8, value: "Hoàng Sa" },
];
const dongNai = [
  { id: 1, value: "Biên Hòa" },
  { id: 2, value: "Long Khánh" },
  { id: 3, value: "Cẩm Mỹ" },
  { id: 4, value: "Định Quán" },
  { id: 5, value: "Long Thành" },
  { id: 6, value: "Nhơn Trạch" },
  { id: 7, value: "Tân Phú" },
  { id: 8, value: "Thống Nhất" },
  { id: 9, value: "Trảng Bom" },
  { id: 10, value: "Vĩnh Cửu" },
  { id: 11, value: "Xuân Lộc" },
];

const haiPhong = [
  { id: 1, value: "Dương Kinh" },
  { id: 2, value: "Đồ Sơn" },
  { id: 3, value: "Hải An" },
  { id: 4, value: "Kiến An" },
  { id: 5, value: "Hồng Bàng" },
  { id: 6, value: "Ngô Quyền" },
  { id: 7, value: "Lê Chân" },
  { id: 8, value: "An Dương" },
  { id: 9, value: "An Lão" },
  { id: 10, value: "Bạch Long Vĩ" },
  { id: 11, value: "Cát Hải" },
  { id: 12, value: "Kiến Thụy" },
  { id: 13, value: "Tiên Lãng" },
  { id: 14, value: "Vĩnh Bảo" },
  { id: 15, value: "Thủy Nguyên" },
];

const anGiang = [
  { id: 1, value: "Châu Đốc" },
  { id: 2, value: "Long Xuyên" },
  { id: 3, value: "Tân Châu" },
  { id: 4, value: "An Phú" },
  { id: 5, value: "Châu Phú" },
  { id: 6, value: "Châu Thành" },
  { id: 7, value: "Chợ Mới" },
  { id: 8, value: "Phú Tân" },
  { id: 9, value: "Thoại Sơn" },
  { id: 10, value: "Tịnh Biên" },
  { id: 11, value: "Tri Tôn" },
];

const baRiaVungTau = [
  { id: 1, value: "Bà Rịa" },
  { id: 2, value: "Vũng Tàu" },
  { id: 3, value: "Phú Mỹ" },
  { id: 4, value: "Châu Đức" },
  { id: 5, value: "Côn Đảo" },
  { id: 6, value: "Đất Đỏ" },
  { id: 7, value: "Long Điền" },
  { id: 8, value: "Xuyên Mộc" },
];
const bacGiang = [
  { id: 1, value: "Bắc Giang" },
  { id: 2, value: "Hiệp Hòa" },
  { id: 3, value: "Lạng Giang" },
  { id: 4, value: "Lục Nam" },
  { id: 5, value: "Lục Ngạn" },
  { id: 6, value: "Sơn Động" },
  { id: 7, value: "Tân Yên" },
  { id: 8, value: "Việt Yên" },
  { id: 9, value: "Yên Dũng" },
  { id: 10, value: "Yên Thế" },
];

const bacKan = [
  { id: 1, value: "Bắc Kạn" },
  { id: 2, value: "Ba Bể" },
  { id: 3, value: "Bạch Thông" },
  { id: 4, value: "Chợ Đồn" },
  { id: 5, value: "Chợ Mới" },
  { id: 6, value: "Na Rì" },
  { id: 7, value: "Ngân Sơn" },
  { id: 8, value: "Pác Nặm" },
];
const bacLieu = [
  { id: 1, value: "Bạc Liêu" },
  { id: 2, value: "Giá Rai" },
  { id: 3, value: "Đông Hải" },
  { id: 4, value: "Hòa Binh" },
  { id: 5, value: "Hồng Dân" },
  { id: 6, value: "Phước Long" },
  { id: 7, value: "Vĩnh Lợi" },
];
const bacNinh = [
  { id: 1, value: "Bắc Ninh" },
  { id: 2, value: "Từ Sơn" },
  { id: 3, value: "Gia Bình" },
  { id: 4, value: "Lương Tài" },
  { id: 5, value: "Quế Võ" },
  { id: 6, value: "Thuận Thành" },
  { id: 7, value: "Tiên Du" },
  { id: 8, value: "Yên Phong" },
];
const benTre = [
  { id: 1, value: "Bến Tre" },
  { id: 2, value: "Ba Tri" },
  { id: 3, value: "Bình Đại" },
  { id: 4, value: "Châu Thành" },
  { id: 5, value: "Chợ Lách" },
  { id: 6, value: "Giồng Trôm" },
  { id: 7, value: "Mỏ Cày Bắc" },
  { id: 8, value: "Mỏ Cày Nam" },
  { id: 9, value: "Thạnh Phú" },
];
const binhDinh = [
  { id: 1, value: "Quy Nhơn" },
  { id: 2, value: "An Nhơn" },
  { id: 3, value: "Hoài Nhơn" },
  { id: 4, value: "An Lão" },
  { id: 5, value: "Hoài Ân" },
  { id: 6, value: "Phù Cát" },
  { id: 7, value: "Phù Mỹ" },
  { id: 8, value: "Tuy Phước" },
  { id: 9, value: "Tây Sơn" },
  { id: 10, value: "Vân Canh" },
  { id: 11, value: "Vĩnh Thạnh" },
];
const binhDuong = [
  { id: 1, value: "Thủ Dầu Một" },
  { id: 2, value: "Dĩ An" },
  { id: 3, value: "Thuận An" },
  { id: 4, value: "Bến Cát" },
  { id: 5, value: "Tân Uyên" },
  { id: 6, value: "Bàu Bàng" },
  { id: 7, value: "Bắc Tân Uyên" },
  { id: 8, value: "Dầu Tiếng" },
  { id: 9, value: "Phú Giáo" },
];

const binhPhuoc = [
  { id: 1, value: "Đồng Xoài" },
  { id: 2, value: "Bình Long" },
  { id: 3, value: "Phước Long" },
  { id: 4, value: "Bù Đăng" },
  { id: 5, value: "Bù Đốp" },
  { id: 6, value: "Bù Gia Mập" },
  { id: 7, value: "Phú Riềng" },
  { id: 8, value: "Chơn Thành" },
  { id: 9, value: "Đồng Phú" },
  { id: 10, value: "Hớn Quản" },
  { id: 11, value: "Lộc Ninh" },
];
const binhThuan = [
  { id: 1, value: "Phan Thiết" },
  { id: 2, value: "La Gi" },
  { id: 3, value: "Bắc Bình" },
  { id: 4, value: "Đức Linh" },
  { id: 5, value: "Hàm Thuận Bắc" },
  { id: 6, value: "Hàm Thuận Nam" },
  { id: 7, value: "Hàm Tân" },
  { id: 8, value: "Phú Quý" },
  { id: 9, value: "Tánh Linh" },
  { id: 10, value: "Tuy Phong" },
];

const caMau = [
  { id: 1, value: "Cà Mau" },
  { id: 2, value: "Cái Nước" },
  { id: 3, value: "Đầm Dơi" },
  { id: 4, value: "Năm Căn" },
  { id: 5, value: "Ngọc Hiển" },
  { id: 6, value: "Phú Tân" },
  { id: 7, value: "Thới Bình" },
  { id: 8, value: "Trần Văn Thời" },
  { id: 9, value: "U Minh" },
];

const caoBang = [
  { id: 1, value: "Cao Bằng" },
  { id: 2, value: "Bảo Lạc" },
  { id: 3, value: "Bảo Lâm" },
  { id: 4, value: "Hạ Lang" },
  { id: 5, value: "Hà Quảng" },
  { id: 6, value: "Hòa An" },
  { id: 7, value: "Nguyên Bình" },
  { id: 8, value: "Quảng Hòa" },
  { id: 9, value: "Thạch An" },
  { id: 10, value: "Trùng Khánh" },
];
const dakLak = [
  { id: 1, value: "Buôn Ma Thuột" },
  { id: 2, value: "Buôn Hồ" },
  { id: 3, value: "Buôn Đôn" },
  { id: 4, value: "Cư Kuin" },
  { id: 5, value: "Cư M'gar" },
  { id: 6, value: "Ea H'leo" },
  { id: 7, value: "Ea Kar" },
  { id: 8, value: "Ea Súp" },
  { id: 9, value: "Krông Ana" },
  { id: 10, value: "Krông Bông" },
  { id: 11, value: "Krông Búk" },
  { id: 12, value: "Krông Năng" },
  { id: 13, value: "Krông Pắc" },
  { id: 14, value: "Lắk" },
  { id: 15, value: "M'Drắk" },
];
const dakNong = [
  { id: 1, value: "Gia Nghĩa" },
  { id: 2, value: "Cư Jút" },
  { id: 3, value: "Đăk Glong" },
  { id: 4, value: "Đăk Mil" },
  { id: 5, value: "Đăk R'Lấp" },
  { id: 6, value: "Đăk Song" },
  { id: 7, value: "Krông Nô" },
  { id: 8, value: "Tuy Đức" },
];
const dienBien = [
  { id: 1, value: "Điện Biên Phủ" },
  { id: 2, value: "Mường Lay" },
  { id: 3, value: "Điện Biên" },
  { id: 4, value: "Điện Biên Đông" },
  { id: 5, value: "Mường Ảng" },
  { id: 6, value: "Mường Chà" },
  { id: 7, value: "Mường Nhé" },
  { id: 8, value: "Nậm Pồ" },
  { id: 9, value: "Tủa Chùa" },
  { id: 10, value: "Tuần Giáo" },
];
const dongThap = [
  { id: 1, value: "Cao Lãnh" },
  { id: 2, value: "Hồng Ngự" },
  { id: 3, value: "Sa Đéc" },
  { id: 4, value: "Cao Lãnh" },
  { id: 5, value: "Châu Thành" },
  { id: 6, value: "Hồng Ngự" },
  { id: 7, value: "Lai Vung" },
  { id: 8, value: "Lấp Vò" },
  { id: 9, value: "Tam Nông" },
  { id: 10, value: "Tân Hồng" },
  { id: 11, value: "Thanh Bình" },
  { id: 12, value: "Tháp Mười" },
];
const giaLai = [
  { id: 1, value: "Pleiku" },
  { id: 2, value: "An Khê" },
  { id: 3, value: "Ayun Pa" },
  { id: 4, value: "Chư Păh" },
  { id: 5, value: "Chư Prông" },
  { id: 6, value: "Chư Pưh" },
  { id: 7, value: "Chư Sê" },
  { id: 8, value: "Đắk Đoa" },
  { id: 9, value: "Đắk Pơ" },
  { id: 10, value: "Đức Cơ" },
  { id: 11, value: "Ia Grai" },
  { id: 12, value: "Ia Pa" },
  { id: 13, value: "K'Bang" },
  { id: 14, value: "Kông Chro" },
  { id: 15, value: "Krông Pa" },
  { id: 16, value: "Mang Yang" },
  { id: 17, value: "Phú Thiện" },
];
const haGiang = [
  { id: 1, value: "Hà Giang" },
  { id: 2, value: "Bắc Mê" },
  { id: 3, value: "Bắc Quang" },
  { id: 4, value: "Đồng Văn" },
  { id: 5, value: "Hoàng Su Phì" },
  { id: 6, value: "Mèo Vạc" },
  { id: 7, value: "Quản Bạ" },
  { id: 8, value: "Quang Bình" },
  { id: 9, value: "Vị Xuyên" },
  { id: 10, value: "Xín Mần" },
  { id: 11, value: "Yên Minh" },
];
const haNam = [
  { id: 1, value: "Phủ Lý" },
  { id: 2, value: "Duy Tiên" },
  { id: 3, value: "Bình Lục" },
  { id: 4, value: "Kim Bảng" },
  { id: 5, value: "Lý Nhân" },
  { id: 6, value: "Thanh Liêm" },
];
const haTinh = [
  { id: 1, value: "Hà Tĩnh" },
  { id: 2, value: "Hồng Lĩnh" },
  { id: 3, value: "Kỳ Anh" },
  { id: 4, value: "Cẩm Xuyên" },
  { id: 5, value: "Can Lộc" },
  { id: 6, value: "Đức Thọ" },
  { id: 7, value: "Hương Khê" },
  { id: 8, value: "Hương Sơn" },
  { id: 9, value: "Kỳ Anh" },
  { id: 10, value: "Lộc Hà" },
  { id: 11, value: "Nghi Xuân" },
  { id: 12, value: "Thạch Hà" },
  { id: 13, value: "Vũ Quang" },
];
const haiDuong = [
  { id: 1, value: "Hải Dương" },
  { id: 2, value: "Chí Linh" },
  { id: 3, value: "Bình Giang" },
  { id: 4, value: "Cẩm Giàng" },
  { id: 5, value: "Gia Lộc" },
  { id: 6, value: "Kim Thành" },
  { id: 7, value: "Kinh Môn" },
  { id: 8, value: "Nam Sách" },
  { id: 9, value: "Ninh Giang" },
  { id: 10, value: "Thanh Hà" },
  { id: 11, value: "Thanh Miện" },
  { id: 12, value: "Tứ Kỳ" },
];
const hauGiang = [
  { id: 1, value: "Vị Thanh" },
  { id: 2, value: "Ngã Bảy" },
  { id: 3, value: "Long Mỹ" },
  { id: 4, value: "Châu Thành" },
  { id: 5, value: "Châu Thành A" },
  { id: 6, value: "Long Mỹ" },
  { id: 7, value: "Phụng Hiệp" },
  { id: 8, value: "Vị Thủy" },
];
const hoaBinh = [
  { id: 1, value: "Hòa Bình" },
  { id: 2, value: "Cao Phong" },
  { id: 3, value: "Đà Bắc" },
  { id: 4, value: "Kim Bôi" },
  { id: 5, value: "Lạc Sơn" },
  { id: 6, value: "Lạc Thủy" },
  { id: 7, value: "Lương Sơn" },
  { id: 8, value: "Mai Châu" },
  { id: 9, value: "Tân Lạc" },
  { id: 10, value: "Yên Thủy" },
];
const hungYen = [
  { id: 1, value: "Hưng Yên" },
  { id: 2, value: "Mỹ Hào" },
  { id: 3, value: "Ân Thi" },
  { id: 4, value: "Khoái Châu" },
  { id: 5, value: "Kim Động" },
  { id: 6, value: "Phù Cừ" },
  { id: 7, value: "Tiên Lữ" },
  { id: 8, value: "Văn Giang" },
  { id: 9, value: "Văn Lâm" },
  { id: 10, value: "Yên Mỹ" },
];

const khanhHoa = [
  { id: 1, value: "Nha Trang" },
  { id: 2, value: "Cam Ranh" },
  { id: 3, value: "Ninh Hòa" },
  { id: 4, value: "Cam Lâm" },
  { id: 5, value: "Diên Khánh" },
  { id: 6, value: "Khánh Sơn" },
  { id: 7, value: "Khánh Vĩnh" },
  { id: 8, value: "Trường Sa" },
  { id: 9, value: "Vạn Ninh" },
];

const kienGiang = [
  { id: 1, value: "Rạch Giá" },
  { id: 2, value: "Phú Quốc Island" },
  { id: 3, value: "Hà Tiên" },
  { id: 4, value: "An Biên" },
  { id: 5, value: "An Minh" },
  { id: 6, value: "Châu Thành" },
  { id: 7, value: "Giang Thành" },
  { id: 8, value: "Giồng Riềng" },
  { id: 9, value: "Gò Quao" },
  { id: 10, value: "Hòn Đất" },
  { id: 11, value: "Kiên Hải Island" },
  { id: 12, value: "Kiên Lương" },
  { id: 13, value: "Tân Hiệp" },
  { id: 14, value: "Vĩnh Thuận" },
  { id: 15, value: "U Minh Thượng" },
];

const konTum = [
  { id: 1, value: "Kon Tum" },
  { id: 2, value: "Đắk Glei" },
  { id: 3, value: "Đắk Hà" },
  { id: 4, value: "Đắk Tô" },
  { id: 5, value: "Ia H'Drai" },
  { id: 6, value: "Kon Plông" },
  { id: 7, value: "Kon Rẫy" },
  { id: 8, value: "Ngọc Hồi" },
  { id: 9, value: "Sa Thầy" },
  { id: 10, value: "Tu Mơ Rông" },
];

const laiChau = [
  { id: 1, value: "Lai Châu" },
  { id: 2, value: "Mường Tè" },
  { id: 3, value: "Nậm Nhùn" },
  { id: 4, value: "Phong Thổ" },
  { id: 5, value: "Sìn Hồ" },
  { id: 6, value: "Tam Dương" },
  { id: 7, value: "Than Uyên" },
  { id: 8, value: "Tân Uyên" },
];

const lamDong = [
  { id: 1, value: "Bảo Lộc" },
  { id: 2, value: "Da Lat" },
  { id: 3, value: "Bảo Lâm" },
  { id: 4, value: "Cát Tiên" },
  { id: 5, value: "Đạ Huoai" },
  { id: 6, value: "Đạ Tẻh" },
  { id: 7, value: "Đam Rông" },
  { id: 8, value: "Di Linh" },
  { id: 9, value: "Đơn Dương" },
  { id: 10, value: "Đức Trọng" },
  { id: 11, value: "Lạc Dương" },
  { id: 12, value: "Lâm Hà" },
];

const langSon = [
  { id: 1, value: "Lạng Sơn" },
  { id: 2, value: "Bắc Sơn" },
  { id: 3, value: "Bình Gia" },
  { id: 4, value: "Cao Lộc" },
  { id: 5, value: "Chi Lăng" },
  { id: 6, value: "Đình Lập" },
  { id: 7, value: "Hữu Lũng" },
  { id: 8, value: "Lộc Bình" },
  { id: 9, value: "Tràng Định" },
  { id: 10, value: "Văn Lãng" },
  { id: 11, value: "Văn Quan" },
];

const laoCai = [
  { id: 1, value: "Lào Cai" },
  { id: 2, value: "Sa Pa" },
  { id: 3, value: "Bắc Hà" },
  { id: 4, value: "Bảo Thắng" },
  { id: 5, value: "Bảo Yên" },
  { id: 6, value: "Bát Xát" },
  { id: 7, value: "Mường Khương" },
  { id: 8, value: "Si Ma Cai" },
  { id: 9, value: "Văn Bàn" },
];
const longAn = [
  { id: 1, value: "Tân An" },
  { id: 2, value: "Kiến Tường" },
  { id: 3, value: "Bến Lức" },
  { id: 4, value: "Cần Đước" },
  { id: 5, value: "Cần Giuộc" },
  { id: 6, value: "Châu Thành" },
  { id: 7, value: "Đức Hòa" },
  { id: 8, value: "Đức Huệ" },
  { id: 9, value: "Mộc Hóa" },
  { id: 10, value: "Tân Hưng" },
  { id: 11, value: "Tân Thạnh" },
  { id: 12, value: "Tân Trụ" },
  { id: 13, value: "Thạnh Hóa" },
  { id: 14, value: "Thủ Thừa" },
  { id: 15, value: "Vĩnh Hưng" },
];

const namDinh = [
  { id: 1, value: "Nam Định" },
  { id: 2, value: "Giao Thủy" },
  { id: 3, value: "Hải Hậu" },
  { id: 4, value: "Mỹ Lộc" },
  { id: 5, value: "Nam Trực" },
  { id: 6, value: "Nghĩa Hưng" },
  { id: 7, value: "Trực Ninh" },
  { id: 8, value: "Vụ Bản" },
  { id: 9, value: "Xuân Trường" },
  { id: 10, value: "Ý Yên" },
];

const ngheAn = [
  { id: 1, value: "Vinh" },
  { id: 2, value: "Cửa Lò" },
  { id: 3, value: "Thái Hòa" },
  { id: 4, value: "Hoàng Mai" },
  { id: 5, value: "Anh Sơn" },
  { id: 6, value: "Con Cuông" },
  { id: 7, value: "Diễn Châu" },
  { id: 8, value: "Đô Lương" },
  { id: 9, value: "Hưng Nguyên" },
  { id: 10, value: "Kỳ Sơn" },
  { id: 11, value: "Nam Đàn" },
  { id: 12, value: "Nghi Lộc" },
  { id: 13, value: "Nghĩa Đàn" },
  { id: 14, value: "Quế Phong" },
  { id: 15, value: "Quỳ Châu" },
  { id: 16, value: "Quỳ Hợp" },
  { id: 17, value: "Quỳnh Lưu" },
  { id: 18, value: "Tân Kỳ" },
  { id: 19, value: "Thanh Chương" },
  { id: 20, value: "Tương Dương" },
  { id: 21, value: "Yên Thàn" },
];
//index 41
const ninhBinh = [
  { id: 1, value: "Ninh Bình" },
  { id: 2, value: "Tam Điệp" },
  { id: 3, value: "Gia Viễn" },
  { id: 4, value: "Hoa Lư" },
  { id: 5, value: "Kim Sơn" },
  { id: 6, value: "Nho Quan" },
  { id: 7, value: "Yên Khánh" },
  { id: 8, value: "Yên Mô" },
];
const ninhThuan = [
  { id: 1, value: "Phan Rang Tháp Chàm" },
  { id: 2, value: "Bác Ái" },
  { id: 3, value: "Ninh Hải" },
  { id: 4, value: "Ninh Phước" },
  { id: 5, value: "Ninh Sơn" },
  { id: 6, value: "Thuận Bắc" },
  { id: 7, value: "Thuận Nam" },
];
const phuTho = [
  { id: 1, value: "Việt Trì" },
  { id: 2, value: "Phú Thọ" },
  { id: 3, value: "Cẩm Khê" },
  { id: 4, value: "Đoan Hùng" },
  { id: 5, value: "Hạ Hòa" },
  { id: 6, value: "Lâm Thao" },
  { id: 7, value: "Phù Ninh" },
  { id: 8, value: "Tam Nông" },
  { id: 9, value: "Tân Sơn" },
  { id: 10, value: "Thanh Ba" },
  { id: 11, value: "Thanh Sơn" },
  { id: 12, value: "Thanh Thủy" },
  { id: 13, value: "Yên Lập" },
];

const phuYen = [
  { id: 1, value: "Tuy Hòa" },
  { id: 2, value: "Đông Hòa" },
  { id: 3, value: "Sông Cầu" },
  { id: 4, value: "Đồng Xuân" },
  { id: 5, value: "Phú Hòa" },
  { id: 6, value: "Sơn Hòa" },
  { id: 7, value: "Sông Hinh" },
  { id: 8, value: "Tây Hòa" },
  { id: 9, value: "Tuy An" },
];

const quangBinh = [
  { id: 1, value: "Đồng Hới" },
  { id: 2, value: "Ba Đồn" },
  { id: 3, value: "Bố Trạch" },
  { id: 4, value: "Lệ Thủy" },
  { id: 5, value: "Minh Hóa" },
  { id: 6, value: "Quảng Ninh" },
  { id: 7, value: "Quảng Trạch" },
  { id: 8, value: "Tuyên Hóa" },
];

const quangNam = [
  { id: 1, value: "Hội An" },
  { id: 2, value: "Tam Kỳ" },
  { id: 3, value: "Điện Bàn" },
  { id: 4, value: "Bắc Trà My" },
  { id: 5, value: "Duy Xuyên" },
  { id: 6, value: "Đại Lộc" },
  { id: 7, value: "Điện Bàn" },
  { id: 8, value: "Đông Giang" },
  { id: 9, value: "Hiệp Đức" },
  { id: 10, value: "Nam Giang" },
  { id: 11, value: "Nam Trà My" },
  { id: 12, value: "Núi Thành" },
  { id: 13, value: "Phú Ninh" },
  { id: 14, value: "Phước Sơn" },
  { id: 15, value: "Quế Sơn" },
  { id: 16, value: "Tây Giang" },
  { id: 17, value: "Thăng Bình" },
  { id: 18, value: "Tiên Phước" },
  { id: 19, value: "Nông Sơn" },
];

const quangNgai = [
  { id: 1, value: "Quảng Ngãi" },
  { id: 2, value: "Đức Phổ" },
  { id: 3, value: "Ba Tơ" },
  { id: 4, value: "Bình Sơn" },
  { id: 5, value: "Minh Long" },
  { id: 6, value: "Mộ Đức" },
  { id: 7, value: "Nghĩa Hành" },
  { id: 8, value: "Sơn Hà" },
  { id: 9, value: "Sơn Tây" },
  { id: 10, value: "Sơn Tịnh" },
  { id: 11, value: "Tây Trà" },
  { id: 12, value: "Trà Bồng" },
  { id: 13, value: "Tư Nghĩa" },
  { id: 14, value: "Lý Sơn" },
];

const quangNinh = [
  { id: 1, value: "Hạ Long" },
  { id: 2, value: "Uông Bí" },
  { id: 3, value: "Móng Cái" },
  { id: 4, value: "Cẩm Phả" },
  { id: 5, value: "Quảng Yên" },
  { id: 6, value: "Đông Triều" },
  { id: 7, value: "Cô Tô" },
  { id: 8, value: "Đầm Hà" },
  { id: 9, value: "Hải Hà" },
  { id: 10, value: "Vân Đồn" },
  { id: 11, value: "Bình Liêu" },
  { id: 12, value: "Ba Chẽ" },
  { id: 13, value: "Tiên Yên" },
];

const quangTri = [
  { id: 1, value: "Đông Hà" },
  { id: 2, value: "Quảng Trị" },
  { id: 3, value: "Cam Lộ" },
  { id: 4, value: "Cồn Cỏ" },
  { id: 5, value: "Đa Krông" },
  { id: 6, value: "Gio Linh" },
  { id: 7, value: "Hải Lăng" },
  { id: 8, value: "Hướng Hóa" },
  { id: 9, value: "Triệu Phong" },
  { id: 10, value: "Vĩnh Linh" },
];

const socTrang = [
  { id: 1, value: "Sóc Trăng" },
  { id: 2, value: "Vĩnh Châu" },
  { id: 3, value: "Ngã Năm" },
  { id: 4, value: "Châu Thành" },
  { id: 5, value: "Cù Lao Dung" },
  { id: 6, value: "Kế Sách" },
  { id: 7, value: "Long Phú" },
  { id: 8, value: "Mỹ Tú" },
  { id: 9, value: "Mỹ Xuyên" },
  { id: 10, value: "Thạnh Trị" },
  { id: 11, value: "Trần Đề" },
];

const sonLa = [
  { id: 1, value: "Sơn La" },
  { id: 2, value: "Bắc Yên" },
  { id: 3, value: "Mai Sơn" },
  { id: 4, value: "Mộc Châu" },
  { id: 5, value: "Mường La" },
  { id: 6, value: "Phù Yên" },
  { id: 7, value: "Quỳnh Nhai" },
  { id: 8, value: "Sông Mã" },
  { id: 9, value: "Sốp Cộp" },
  { id: 10, value: "Thuận Châu" },
  { id: 11, value: "Vân Hồ" },
  { id: 12, value: "Yên Châu" },
];

const tayNinh = [
  { id: 1, value: "Tây Ninh" },
  { id: 2, value: "Hòa Thành" },
  { id: 3, value: "Trảng Bàng" },
  { id: 4, value: "Bến Cầu" },
  { id: 5, value: "Châu Thành" },
  { id: 6, value: "Dương Minh Châu" },
  { id: 7, value: "Gò Dầu" },
  { id: 8, value: "Tân Biên" },
  { id: 9, value: "Tân Châu" },
];

const thaiBinh = [
  { id: 1, value: "Thái Bình" },
  { id: 2, value: "Đông Hưng" },
  { id: 3, value: "Hưng Hà" },
  { id: 4, value: "Kiến Xương" },
  { id: 5, value: "Quỳnh Phụ" },
  { id: 6, value: "Thái Thụy" },
  { id: 7, value: "Tiền Hải" },
  { id: 8, value: "Vũ Thư" },
];

const thaiNguyen = [
  { id: 1, value: "Thái Nguyên" },
  { id: 2, value: "Sông Công" },
  { id: 3, value: "Phổ Yên" },
  { id: 4, value: "Đại Từ" },
  { id: 5, value: "Định Hóa" },
  { id: 6, value: "Đồng Hỷ" },
  { id: 7, value: "Phú Bình" },
  { id: 8, value: "Phú Lương" },
  { id: 9, value: "Võ Nhai" },
];

const thanhHoa = [
  { id: 1, value: "Thanh Hóa" },
  { id: 2, value: "Sầm Sơn" },
  { id: 3, value: "Bỉm Sơn" },
  { id: 4, value: "Nghi Sơn" },
  { id: 5, value: "Bá Thước" },
  { id: 6, value: "Cẩm Thủy" },
  { id: 7, value: "Đông Sơn" },
  { id: 8, value: "Hà Trung" },
  { id: 9, value: "Hậu Lộc" },
  { id: 10, value: "Hoằng Hóa" },
  { id: 11, value: "Lang Chánh" },
  { id: 12, value: "Mường Lát" },
  { id: 13, value: "Nga Sơn" },
  { id: 14, value: "Ngọc Lặc" },
  { id: 15, value: "Như Thanh" },
  { id: 16, value: "Như Xuân" },
  { id: 17, value: "Nông Cống" },
  { id: 18, value: "Quan Hóa" },
  { id: 19, value: "Quan Sơn" },
  { id: 20, value: "Quảng Xương" },
  { id: 21, value: "Thạch Thành" },
  { id: 22, value: "Thiệu Hóa" },
  { id: 23, value: "Thọ Xuân" },
  { id: 24, value: "Thường Xuân" },
  { id: 25, value: "Triệu Sơn" },
  { id: 26, value: "Vĩnh Lộc" },
  { id: 27, value: "Yên Định" },
];

const thuaThienHue = [
  { id: 1, value: "Huế" },
  { id: 2, value: "Hương Thủy" },
  { id: 3, value: "Hương Trà" },
  { id: 4, value: "A Lưới" },
  { id: 5, value: "Nam Đông" },
  { id: 6, value: "Phong Điền" },
  { id: 7, value: "Phú Lộc" },
  { id: 8, value: "Phú Vang" },
  { id: 9, value: "Quảng Điền" },
];

const tienGiang = [
  { id: 1, value: "Mỹ Tho" },
  { id: 2, value: "Cai Lậy" },
  { id: 3, value: "Gò Công" },
  { id: 4, value: "Cái Bè" },
  { id: 5, value: "Cai Lậy" },
  { id: 6, value: "Châu Thành" },
  { id: 7, value: "Chợ Gạo" },
  { id: 8, value: "Gò Công Đông" },
  { id: 9, value: "Gò Công Tây" },
  { id: 10, value: "Tân Phú Đông" },
  { id: 11, value: "Tân Phước" },
];

const traVinh = [
  { id: 1, value: "Trà Vinh" },
  { id: 2, value: "Duyên Hải" },
  { id: 3, value: "Càng Long" },
  { id: 4, value: "Cầu Kè" },
  { id: 5, value: "Cầu Ngang" },
  { id: 6, value: "Châu Thành" },
  { id: 7, value: "Duyên Hải" },
  { id: 8, value: "Tiểu Cần" },
  { id: 9, value: "Trà Cú" },
];

const tuyenQuang = [
  { id: 1, value: "Tuyên Quang" },
  { id: 2, value: "Chiêm Hoá" },
  { id: 3, value: "Hàm Yên" },
  { id: 4, value: "Lâm Bình" },
  { id: 5, value: "Na Hang" },
  { id: 6, value: "Sơn Dương" },
  { id: 7, value: "Yên Sơn" },
];

const vinhLong = [
  { id: 1, value: "Vĩnh Long" },
  { id: 2, value: "Bình Minh" },
  { id: 3, value: "Bình Tân" },
  { id: 4, value: "Long Hồ" },
  { id: 5, value: "Mang Thít" },
  { id: 6, value: "Tam Bình" },
  { id: 7, value: "Trà Ôn" },
  { id: 8, value: "Vũng Liêm" },
];

const vinhPhuc = [
  { id: 1, value: "Vĩnh Yên" },
  { id: 2, value: "Phúc Yên" },
  { id: 3, value: "Sông Lô" },
  { id: 4, value: "Bình Xuyên" },
  { id: 5, value: "Lập Thạch" },
  { id: 6, value: "Tam Đảo" },
  { id: 7, value: "Tam Dương" },
  { id: 8, value: "Vĩnh Tường" },
  { id: 9, value: "Yên Lạc" },
];

const yenBai = [
  { id: 1, value: "Yên Bái" },
  { id: 2, value: "Nghĩa Lộ" },
  { id: 3, value: "Lục Yên" },
  { id: 4, value: "Mù Cang Chải" },
  { id: 5, value: "Trạm Tấu" },
  { id: 6, value: "Trấn Yên" },
  { id: 7, value: "Văn Chấn" },
  { id: 8, value: "Văn Yên" },
  { id: 9, value: "Yên Bình" },
];

//2급 행정구 배열
export const smallDistrict = [
  vnNull,
  haNoi,
  hoChiMinh,
  canTho,
  daNang,
  dongNai,
  haiPhong,
  anGiang,
  baRiaVungTau,
  bacGiang,
  bacKan,
  bacLieu,
  bacNinh,
  benTre,
  binhDinh,
  binhDuong,
  binhPhuoc,
  binhThuan,
  caMau,
  caoBang,
  dakLak,
  dakNong,
  dienBien,
  dongThap,
  giaLai,
  haGiang,
  haNam,
  haTinh,
  haiDuong,
  hauGiang,
  hoaBinh,
  hungYen,
  khanhHoa,
  kienGiang,
  konTum,
  laiChau,
  lamDong,
  langSon,
  laoCai,
  longAn,
  namDinh,
  ngheAn,
  ninhBinh,
  ninhThuan,
  phuTho,
  phuYen,
  quangBinh,
  quangNam,
  quangNgai,
  quangNinh,
  quangTri,
  socTrang,
  sonLa,
  tayNinh,
  thaiBinh,
  thaiNguyen,
  thanhHoa,
  thuaThienHue,
  tienGiang,
  traVinh,
  tuyenQuang,
  vinhLong,
  vinhPhuc,
  yenBai,
];
